# Generated by Django 5.2.6 on 2025-09-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_age_user_bio_user_gender_user_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_super",
            field=models.BooleanField(default=False),
        ),
    ]
