# Generated by Django 5.2.6 on 2025-09-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_super"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("trainer", "Trainer"),
                    ("member", "Member"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
