# Generated by Django 5.2.6 on 2025-09-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_options_alter_user_role_alter_user_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, help_text="User's age in years", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, help_text="User's biography or description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                help_text="User's gender",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="height",
            field=models.FloatField(
                blank=True, help_text="User's height in centimeters", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="Soft delete flag for this user"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_super",
            field=models.BooleanField(
                default=False, help_text="Whether this user has super admin privileges"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, help_text="User's phone number", max_length=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="User's profile picture",
                null=True,
                upload_to="profile_images/",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("trainer", "Trainer"),
                    ("member", "Member"),
                ],
                help_text="User role in the system (admin, trainer, or member)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="weight",
            field=models.FloatField(
                blank=True, help_text="User's weight in kilograms", null=True
            ),
        ),
    ]
