# Generated by Django 5.2.6 on 2025-09-16 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NutritionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the nutrition plan", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the nutrition plan"),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        help_text="Type of meal (breakfast, lunch, dinner, snack)",
                        max_length=20,
                    ),
                ),
                (
                    "calories",
                    models.IntegerField(help_text="Total calories for this meal"),
                ),
                (
                    "protein_grams",
                    models.FloatField(help_text="Protein content in grams"),
                ),
                (
                    "carbs_grams",
                    models.FloatField(help_text="Carbohydrate content in grams"),
                ),
                ("fat_grams", models.FloatField(help_text="Fat content in grams")),
                (
                    "meal_details",
                    models.TextField(
                        help_text="Detailed description of the meal and ingredients"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this nutrition plan is currently active",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the nutrition plan was created",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Member assigned to this nutrition plan",
                        limit_choices_to={"role": "member"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_nutrition_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        help_text="Trainer who created this nutrition plan",
                        limit_choices_to={"role": "trainer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_nutrition_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "nutrition_plans",
            },
        ),
    ]
