# Generated by Django 5.2.6 on 2025-09-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("quarterly", "Quarterly"),
                    ("yearly", "Yearly"),
                ],
                max_length=20,
            ),
        ),
    ]
