# Generated by Django 5.2.6 on 2025-09-11 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_alter_membership_plan_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="end_date",
            field=models.DateField(help_text="Membership end date"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this membership is currently active"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="member",
            field=models.ForeignKey(
                help_text="Select the member for this membership",
                limit_choices_to={"role": "member"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("quarterly", "Quarterly"),
                    ("yearly", "Yearly"),
                ],
                help_text="Choose the membership plan type",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="start_date",
            field=models.DateField(help_text="Membership start date"),
        ),
    ]
