# Generated by Django 5.2.6 on 2025-09-11 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("chest", "Chest"),
                            ("back", "Back"),
                            ("shoulders", "Shoulders"),
                            ("biceps", "Biceps"),
                            ("triceps", "Triceps"),
                            ("legs", "Legs"),
                            ("abs", "Abs"),
                            ("cardio", "Cardio"),
                            ("full_body", "Full Body"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("instructions", models.TextField(blank=True, null=True)),
                ("muscle_groups", models.CharField(max_length=200)),
                (
                    "equipment_needed",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("calories_per_minute", models.FloatField(blank=True, null=True)),
                (
                    "exercise_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="exercise_images/"
                    ),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "exercises",
            },
        ),
        migrations.CreateModel(
            name="MemberProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField()),
                ("body_fat_percentage", models.FloatField(blank=True, null=True)),
                ("muscle_mass", models.FloatField(blank=True, null=True)),
                ("measurements", models.JSONField(blank=True, null=True)),
                (
                    "progress_photos",
                    models.ImageField(
                        blank=True, null=True, upload_to="progress_photos/"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("recorded_date", models.DateField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        limit_choices_to={"role": "member"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "member_progress",
            },
        ),
        migrations.CreateModel(
            name="NutritionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        max_length=20,
                    ),
                ),
                ("calories", models.IntegerField()),
                ("protein_grams", models.FloatField()),
                ("carbs_grams", models.FloatField()),
                ("fat_grams", models.FloatField()),
                ("meal_details", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        limit_choices_to={"role": "member"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_nutrition_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        limit_choices_to={"role": "trainer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_nutrition_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "nutrition_plans",
            },
        ),
        migrations.CreateModel(
            name="WorkoutPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("fat_loss", "Fat Loss"),
                            ("weight_loss", "Weight Loss"),
                            ("muscle_gain", "Muscle Gain"),
                            ("strength", "Strength Training"),
                            ("endurance", "Endurance"),
                            ("general_fitness", "General Fitness"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("sunday", "Sunday"),
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration_weeks", models.IntegerField(default=4)),
                ("calories_target", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        limit_choices_to={"role": "member"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_workout_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        limit_choices_to={"role": "trainer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_workout_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workout_plans",
            },
        ),
        migrations.CreateModel(
            name="WorkoutLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("sets_completed", models.IntegerField()),
                ("reps_completed", models.IntegerField()),
                ("weight_used", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout.exercise",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        limit_choices_to={"role": "member"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workout_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="workout.workoutplan",
                    ),
                ),
            ],
            options={
                "db_table": "workout_logs",
            },
        ),
        migrations.CreateModel(
            name="WorkoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("total_calories_burned", models.IntegerField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        limit_choices_to={"role": "member"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workout_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="workout.workoutplan",
                    ),
                ),
            ],
            options={
                "db_table": "workout_sessions",
            },
        ),
        migrations.CreateModel(
            name="TrainerMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "member",
                    models.ForeignKey(
                        limit_choices_to={"role": "member"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_trainer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        limit_choices_to={"role": "trainer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "trainer_members",
                "unique_together": {("trainer", "member")},
            },
        ),
        migrations.CreateModel(
            name="WorkoutPlanExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sets", models.IntegerField()),
                ("reps", models.IntegerField()),
                ("weight", models.FloatField(blank=True, null=True)),
                ("rest_time_seconds", models.IntegerField(default=60)),
                ("order", models.IntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout.exercise",
                    ),
                ),
                (
                    "workout_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_exercises",
                        to="workout.workoutplan",
                    ),
                ),
            ],
            options={
                "db_table": "workout_plan_exercises",
                "unique_together": {("workout_plan", "exercise", "order")},
            },
        ),
    ]
