# Generated by Django 5.2.6 on 2025-09-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workoutsession",
            name="completed",
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default=False,
                help_text="Whether the workout session was completed",
                max_length=20,
            ),
        ),
    ]
